---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shiny
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.shiny.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
              name: {{ .Values.myname }}
              port: 
                  number: 3838

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.studio.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
              name: {{ .Values.myname }}
              port:
                  number: 8787
