---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.myname }}
  labels:
    name: {{ .Values.myname }}
spec:
  type: NodePort
  ports:
  - name: studio
    port: 8787
  - name: shiny
    port: 3838
  selector:
    name: {{ .Values.myname }}


