apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dep.name }}
  labels:
    app: hi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hi
  template:
    metadata:
      labels:
        app: hi
    spec:
      containers:
      - name: hello
        image: hc7docker/hello-node
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: myvolume
          mountPath: /mymount
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}

