apiVersion: v1
kind: Service
metadata:
  labels:
    app: hi
  name: {{ .Values.service.name }}
spec:
  type: NodePort
  ports:
  - name: hi
    port: 8080
  selector:
    app: hi
  sessionAffinity: None
status:
  loadBalancer: {}

