# vim:set sw=2 ts=2 et:
#
# Copyright (c) 2017 Torchbox Ltd.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely. This software is provided 'as-is', without any express or implied
# warranty.


# The default system:persistent-volume-provisioner role in Kubernetes 1.8 is
# insufficient:
#
# I1007 18:09:10.073558       1 controller.go:874] cannot start watcher for PVC default/testpvc: events is forbidden: User "system:serviceaccount:kube-system:hostpath-provi$

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hostpath-provisioner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostpath-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hostpath-provisioner

    spec:
      serviceAccountName: hostpath-provisioner

      volumes:
      - name: volumes
        hostPath:
          path: {{ .Values.path }}

      containers:
      - name: hostpath-provisioner
        image: torchbox/k8s-hostpath-provisioner:latest

        volumeMounts:
        - name: volumes
          mountPath: {{ .Values.path }}

        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
